-- CONSULTAS QUE TEM O GEORGE
-- QUANTIDADE DE AMOSTRAS APROVADAS PELO GEORGE
SELECT    
    barcode
FROM dados_api_sp
    WHERE GEORGE IS TRUE;

-- QUANTIDADE DE GÊNEROS APROVADOS PELO GEORGE
SELECT COUNT(DISTINCT genus) FROM dados_api_sp WHERE GEORGE IS TRUE;

-- QUANTIDADE DE AMOSTRAS POR GÊNERO APROVADOS PELO GEORGE
SELECT DISTINCT genus, COUNT(*) FROM dados_api_sp WHERE GEORGE IS TRUE GROUP BY genus;

-- QUANTIDADE DE ESPÉCIES
SELECT COUNT(DISTINCT infraspecific_epithet) FROM dados_api_sp WHERE GEORGE IS TRUE;

-- QUANTIDADE DE AMOSTRAS POR ESPÉCIE
SELECT DISTINCT specific_epithet, COUNT(*) AS QUANTIDADE FROM dados_api_sp WHERE GEORGE IS TRUE GROUP BY specific_epithet ORDER BY QUANTIDADE DESC;

-- QUANTIDADE DE IDENTIFICADORES
SELECT DISTINCT identified_by, COUNT(*) AS QUANTIDADE FROM dados_api_sp WHERE GEORGE IS TRUE GROUP BY identified_by ORDER BY QUANTIDADE DESC;
    
-- AMOSTRAS IGUAIS DO DATASET DO IWSSIP    
SELECT COUNT(*) FROM dados_api_sp JOIN iwssip on dados_api_sp.barcode = iwssip.cod_barra WHERE GEORGE IS TRUE;

-- IDENTIFICADORES DOS GÊNEROS
SELECT identified_by, genus FROM dados_api_sp WHERE GEORGE IS TRUE ORDER BY genus ASC LIMIT 5;

-- VERIFICA SE AS ESPÉCIES QUE ESTÃO NA API SÃO IGUAIS AO SITE
SELECT A.specific_epithet AS AG, A.barcode AS AB, W.species AS WG, W.barcode AS WB
	FROM dados_api_sp AS A
    JOIN dados_web_sp W ON W.barcode=A.barcode
    WHERE GEORGE IS TRUE AND A.specific_epithet<>W.species;	
    
-- APRESENTA OS ESPÉCIES, QUANTIDADE DE AMOSTRAS POR ESPÉCIE E OS SEUS RESPECTIVOS COD_BARRA
SELECT specific_epithet AS ESPÉCIES, COUNT(*) AS QUANTIDADE, GROUP_CONCAT(barcode) AS COD_BARRA
	FROM dados_api_sp
	WHERE GEORGE=TRUE GROUP BY specific_epithet ORDER BY QUANTIDADE DESC;
	
-- APRESENTA OS GÊNEROS, QUANTIDADE DE AMOSTRAS POR GÊNERO E OS SEUS RESPECTIVOS COD_BARRA
SELECT genus AS GÊNEROS, COUNT(*) AS QUANTIDADE, GROUP_CONCAT(barcode) AS COD_BARRA
	FROM dados_api_sp
	WHERE GEORGE=TRUE GROUP BY genus ORDER BY QUANTIDADE DESC;
