INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','S. M. Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Carvalho Silva, M',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, G.P.',false),
	 ('Aline Vieira de Melo Silva','Silva','S. Aparecida Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, FSG',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MF da',false),
	 ('Aline Vieira de Melo Silva','Silva','M. G. da Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Carvalho-Silva, M.; Amorim, P.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MC',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, NT',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','T. Macambo-Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Machado Silva, T.',false),
	 ('Aline Vieira de Melo Silva','Silva','Machado-Silva, T',false),
	 ('Aline Vieira de Melo Silva','Silva','F. Silva Filho',false),
	 ('Aline Vieira de Melo Silva','Silva','F. Bonadeu da Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MCR',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho-Silva/X-2007',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, ACB',false),
	 ('Aline Vieira de Melo Silva','Silva','MICHELINE CARVALHO-SILVA',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho-Silva',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','G. Pereira-Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Carvalho-Silva, M.',false),
	 ('Aline Vieira de Melo Silva','Silva','Macedo-Silva, T.',false),
	 ('Aline Vieira de Melo Silva','Silva','M.Carvalho-Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Carvalho-Silva, M; Pereira, LA',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, C.A.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, R.K.; Seidinger. L.C.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, ACC',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho-Silva/Fev.-2008',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, CAS',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho-Silva/10-08-2006',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, CAS da',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho-Silva, C.C. Silva, et. all',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, S.M.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, BG',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, M.G.',false),
	 ('Aline Vieira de Melo Silva','Silva','Mattos Silva, LA',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho-Silva/X-2006',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MC da',false),
	 ('Aline Vieira de Melo Silva','Silva','Micheline Carvalho Silva',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','Da Silva, D.R.',false),
	 ('Aline Vieira de Melo Silva','Silva','M. C. Silva & C. Sinigaglia',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho Silva/10-08-2006',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva; Carvalho, M',false),
	 ('Aline Vieira de Melo Silva','Silva','Carvalho-Silva M',false),
	 ('Aline Vieira de Melo Silva','Silva','Soares-Silva, J. P.',false),
	 ('Aline Vieira de Melo Silva','Silva','A. G. da Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, T.M.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MFF da',false),
	 ('Aline Vieira de Melo Silva','Silva','M.F.O. Silva et Galvão, M.N.',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','N. T. da Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','M.C. Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MR',false),
	 ('Aline Vieira de Melo Silva','Silva','G. Pereira-Silva & M. Carvalho-Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Fleury-Silva, H.R.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, CSA da',false),
	 ('Aline Vieira de Melo Silva','Silva','A. S. L. da Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','G. P. Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Soares-Silva, J.P.; Sampaio, D.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, DCG',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','Silva Neto, S.J.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, SM',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, M.C.',false),
	 ('Aline Vieira de Melo Silva','Silva','M. Carvalho Silva/X-2008',false),
	 ('Aline Vieira de Melo Silva','Silva','M. A. da Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Caralho Silva, M.',false),
	 ('Aline Vieira de Melo Silva','Silva','Machado-Silva, T.',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, ACC; Melo, A',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, NT da',false),
	 ('Aline Vieira de Melo Silva','Silva','M.A. da Silva',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Aline Vieira de Melo Silva','Silva','Guedes, ML; Silva, LM; Akita, AST',false),
	 ('Aline Vieira de Melo Silva','Silva','Carvalho-Silva, M',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, MG da',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, TT',false),
	 ('Aline Vieira de Melo Silva','Silva','Bernardi, P.T.; Mendes, N.A.; Schinato, F.; Silva, A.L.',false),
	 ('Aline Vieira de Melo Silva','Silva','Machado-Silva',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva, M da',false),
	 ('Aline Vieira de Melo Silva','Silva','Silva',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E. F. et Dmonteiro',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/Jan.2008',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','J.Wesenberg, E.F. Guimarães/02-XII-2009',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães EF; Ichaso CLF',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.; Ichaso, C.L.',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães; C. L. F. Ichaso',true),
	 ('Elsie Franklin Guimarães','Guimar','D. M. Ferreira; E. F. Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.; Queiroz, G.A.',true),
	 ('Elsie Franklin Guimarães','Guimar','Ichaso, C.L.; Guimarães, E.',true),
	 ('Elsie Franklin Guimarães','Guimar','Ichaso, CLF; Guimarães, EF',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.; Ichaso, C.',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães; R. Callejas Posada',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/2005',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.; Ichaso, C.L.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Wesenberg, J',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães & V.B. Sarnaglia-Jr.',true),
	 ('Elsie Franklin Guimarães','Guimar','L.A.Pereira & E.F. Guimarães/24-01-2008',true),
	 ('Elsie Franklin Guimarães','Guimar','E.Guimarães/1992',true),
	 ('Elsie Franklin Guimarães','Guimar','C. L. F. Ichaso; E. F. GuimarÃ£es',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães EF',true),
	 ('Daniele Monteiro Ferreira','Monteiro','H. d. C. Monteiro Filho',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Daniele Monteiro Ferreira','Monteiro','J. Monteiro',false),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro',false),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro, J',false),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro, O',false),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro, OP',false),
	 ('Daniele Monteiro Ferreira','Monteiro','R.Monteiro',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, O.',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimaraes',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; V. Catarelli',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','L.A.Pereira & E.F. Guimarães/25-01-2008',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/2008',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/Out.2008',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães E.F.; Ferreira, D.M.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.; Ichaso, C.L.F.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.; Sanaglia',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimar~eas, E.F.',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/VII-2011',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/2019',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães, E. Medeiros',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães/2009',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. GuimarÃ£es',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','E. Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.G.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.; Ferreira, D.M.',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F.Guimarães/2009',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Ferreira, DM',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães-I/2008',true),
	 ('Elsie Franklin Guimarães','Guimar','D. M. Cavalcanti Ferreira; E. F. Guimarães',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.; Queiroz, G.A.',true),
	 ('Elsie Franklin Guimarães','Guimar','D. Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','O.A. Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, W.',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EL',false),
	 ('Elsie Franklin Guimarães','Guimar','Tais B. Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.K.',false),
	 ('Elsie Franklin Guimarães','Guimar','T. S. Mendes & E.Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, L',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, O',false),
	 ('Elsie Franklin Guimarães','Guimar','O. A. Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/15-05-2013',false),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães/2008',false),
	 ('Elsie Franklin Guimarães','Guimar','E.F.Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/IV-2006',false),
	 ('Elsie Franklin Guimarães','Guimar','C. L. F. Ichaso; E. F. Guimarães',false),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães/2000',false),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães/junho.2008',false),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães-Jan.2008',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.',false),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, O.; Ichaso, C.',false),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','H. Medeiros',false),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','Medeiros',false),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','Medeiros, H',false),
	 ('George Azevedo de Queiroz','Queiroz','L.N.Sátiro & L.P.de Queiroz',false),
	 ('Eric J Tepe','Tepe','Tepe EJ',true),
	 ('George Azevedo de Queiroz','Queiroz','G. A. Queiroz',true),
	 ('George Azevedo de Queiroz','Queiroz','G.A. Queiroz',true),
	 ('George Azevedo de Queiroz','Queiroz','G.A. Queiroz/2018',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('George Azevedo de Queiroz','Queiroz','Guimarães, E.F.; Queiroz, G.A.',true),
	 ('George Azevedo de Queiroz','Queiroz','Guimarães, E.; Queiroz, G.A.',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/2008',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães/2006',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F.Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F.Guimarães & D.Monteiro/04',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E. .F.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Carvalho, M',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/Agos.1991',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães E.F.',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/2016',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.; Sarnaglia Júnior, V.B.',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Callejas, R',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimar~eas, E.F.; Ferreira, D.M.',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/2006',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães; D. M. Ferreira',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Monteiro, D',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E.F.; Costa, C.G.; Falcão, C.L.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães/10-10-2007',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','V. Catarelli; E. Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/1991',true),
	 ('Elsie Franklin Guimarães','Guimar','L.A.Pereira & E.F. Guimarães/17-01-2008',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães/ 1995',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães,E.F.',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimarães - 5/1/2008',true),
	 ('Elsie Franklin Guimarães','Guimar','L.A.Pereira & E.F. Guimarães/26-03-2008',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie Franklin Guimarães',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie Guimarães',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','E.F.Guimarães & D.M. Ferreira/2006',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E. & Ichaso, C.',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F.Guimarães/2006',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/2007',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/1992',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E. & Ichaso,C.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Carvalho, MS',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F.GUIMARÃES',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. GuimarÃ£es; C. L. F. Ichaso',true),
	 ('Elsie Franklin Guimarães','Guimar','R. Callejas Posada; E. F. GuimarÃ£es',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Elsie Franklin Guimarães','Guimar','E. Guimarães/2001',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães/2018',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, E. F.',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF',true),
	 ('Elsie Franklin Guimarães','Guimar','Guimarães, EF; Medeiros, E von S.',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/2003',true),
	 ('Elsie Franklin Guimarães','Guimar','E. Guimarães/2009',true),
	 ('George Azevedo de Queiroz','Queiroz','L. P. de Queiroz',false),
	 ('George Azevedo de Queiroz','Queiroz','L.P.de Queiroz',false),
	 ('George Azevedo de Queiroz','Queiroz','M.H. de Queiroz',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('George Azevedo de Queiroz','Queiroz','Queiroz',false),
	 ('George Azevedo de Queiroz','Queiroz','Queiroz, EP',false),
	 ('George Azevedo de Queiroz','Queiroz','Queiroz, LP de',false),
	 ('George Azevedo de Queiroz','Queiroz','Queiroz, M.H. de',false),
	 ('George Azevedo de Queiroz','Queiroz','Queiroz, MN',false),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho, MLS',false),
	 ('Micheline Carvalho-Silva','Carvalho','J.G.de Carvalho-Sobrinho',false),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho, AM de',false),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho',false),
	 ('Micheline Carvalho-Silva','Carvalho','Silva; Carvalho, M',false);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Micheline Carvalho-Silva','Carvalho','Guimarães, EF; Carvalho, MS',false),
	 ('Micheline Carvalho-Silva','Carvalho','Guimarães, EF; Carvalho, M',false),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho, MS',false),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho-Silva',true),
	 ('Micheline Carvalho-Silva','Carvalho','M.Carvalho-Silva',true),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho-Silva/Fev.-2008',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho-Silva M',true),
	 ('Truman George Yuncker','Yuncker','Yuncker, T.G.',true),
	 ('Truman George Yuncker','Yuncker','W. Trelease; T. G. Yuncker',true),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','Medeiros, E von S',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho-Silva/X-2007',true),
	 ('Truman George Yuncker','Yuncker','G Yuncker, T.',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho-Silva, M',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','R. Callejas Posada',true),
	 ('Truman George Yuncker','Yuncker','T. G.Yuncker',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro, D.',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Guimarães, E. F. et Dmonteiro',true),
	 ('Daniel Ruschel','Ruschel','Daniel Rruschel',true),
	 ('Daniel Ruschel','Ruschel','D. Ruschell',true),
	 ('Daniel Ruschel','Ruschel','Ruschel, D.',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/X-2014',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','R. Callejas',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','R.Callejas',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Guimarães, EF; Callejas, R',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','R. Callejas/1993',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Callejas',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Callejas, R; Garcia, AR',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Ricardo Callejas',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Callejas, R',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Callejas, R.',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Ricardo de la Merced Callejas Posada','Callejas','R. Callejas/1994',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','et al.; Callejas, R',true),
	 ('Micheline Carvalho-Silva','Carvalho','Micheline Carvalho Silva',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho, M',true),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho Silva/10-08-2006',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho Silva, M',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho, M.S.',true),
	 ('George Azevedo de Queiroz','Queiroz','Queiroz, G.A.',true),
	 ('George Azevedo de Queiroz','Queiroz','Queiroz, G.A. de',true),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho-Silva, C.C. Silva, et. all',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho Silva/X-2008',true),
	 ('Elsie Franklin Guimarães','Guimar','Elsie F. Guimaraes',true),
	 ('Eric J Tepe','Tepe','Tepe, EJ',true),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','Guimarães, EF; Medeiros, E von S.',true),
	 ('Eric J Tepe','Tepe','E. J. Tepe',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, O.; Ichaso, C.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Ichaso, CL',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Ichaso, CLF',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Ichaso, C.L.; Guimarães, E.',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Daniele Monteiro',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro',true),
	 ('Truman George Yuncker','Yuncker','Yuncker TG',true),
	 ('William Trelease','Trelease','Trelease, W.; Yuncker, T. G.',true),
	 ('William Trelease','Trelease','W. Trelease; T. G. Yuncker',true),
	 ('Truman George Yuncker','Yuncker','Yuncker, TG',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/15-06-2012',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/20-06-2012',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/2011',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/26-03-2008',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/Março-2008',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('William Trelease','Trelease','Trelease',true),
	 ('William Trelease','Trelease','Trelease, W',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','C. L. F. Ichaso',true),
	 ('Micheline Carvalho-Silva','Carvalho','G. Pereira-Silva & M. Carvalho-Silva',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','E. F. Guimarães; R. Callejas Posada',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','R. Callejas Posada; E. F. GuimarÃ£es',true),
	 ('Truman George Yuncker','Yuncker','Yuncker TG; Trelease W',true),
	 ('Truman George Yuncker','Yuncker','Trelease, W.; Yuncker, T. G.',true),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','Medeiros, ESS',true),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','Medeiros, E von S.',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Micheline Carvalho-Silva','Carvalho','MICHELINE CARVALHO-SILVA',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho-Silva, M.',true),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho-Silva/10-08-2006',true),
	 ('Micheline Carvalho-Silva','Carvalho','M. Carvalho-Silva/X-2006',true),
	 ('Truman George Yuncker','Yuncker','T. G. Yuncker',true),
	 ('Truman George Yuncker','Yuncker','Yuncker, T. G.',true),
	 ('Ricardo de la Merced Callejas Posada','Callejas','Callejas Posada R',true),
	 ('Truman George Yuncker','Yuncker','Yuncker,T.G.',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro, D',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Monteiro, D.M.',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Daniele Monteiro Ferreira','Monteiro','E.F.Guimarães & D.Monteiro/04',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Guimarães, EF; Monteiro, D',true),
	 ('Daniel Ruschel','Ruschel','Daniel Ruschel',true),
	 ('Daniel Ruschel','Ruschel','Ruschel, D',true),
	 ('Elsie Franklin Guimarães','Guimar','E. Guimaraes & C. L. Ichas',true),
	 ('Eric J Tepe','Tepe','Tepe, E.J.',true),
	 ('Erika Von Sohsten de Souza Medeiros','Medeiros','E. F. Guimarães, E. Medeiros',true),
	 ('Eric J Tepe','Tepe','R. C. Foster; E. J. Tepe',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho-Silva, M.; Amorim, P.',true),
	 ('Micheline Carvalho-Silva','Carvalho','Carvalho-Silva, M; Pereira, LA',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Ichaso, C.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Ichaso CLF',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Ichaso, CLF; Guimarães, EF',true),
	 ('Daniele Monteiro Ferreira','Monteiro','Daniela Monteiro',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. F. Monteiro',true),
	 ('William Trelease','Trelease','Yuncker TG; Trelease W',true),
	 ('Aline Vieira de Melo Silva','Silva','A. V. de Melo Silva',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D.Monteiro',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D.Monteiro/15-06-2012',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/2008',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/25-03-2008',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/III-2008',true),
	 ('Daniele Monteiro Ferreira','Monteiro','D. Monteiro/VI-2011',true),
	 ('Truman George Yuncker','Yuncker','Yuncker',true),
	 ('William Trelease','Trelease','Trelease W',true),
	 ('William Trelease','Trelease','Trelease, W.',true),
	 ('William Trelease','Trelease','W. Trelease',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','C. L. F. Ichaso; E. F. GuimarÃ£es',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','C. L. F. Ichaso; E. F. Guimarães',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','E. F. GuimarÃ£es; C. L. F. Ichaso',true);
INSERT INTO public.trusted_identifier ("fullname",search,value_founded,"selected") VALUES
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','E. F. Guimarães; C. L. F. Ichaso',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, E.F.; Ichaso, C.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, E.F.; Ichaso, C.L.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães EF; Ichaso CLF',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, E. & Ichaso, C.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, E. & Ichaso,C.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, E.; Ichaso, C.L.',true),
	 ('Carmen Lúcia Falcão Ichaso','Ichaso','Guimarães, E.; Ichaso, C.L.F.',true),
	 ('Elsie Franklin Guimarães','Guimar','E.F. Guimarães & G.A. Queirox/2017',true),
	 ('Elsie Franklin Guimarães','Guimar','E. F. Guimarães/Agosto.1991',true);
