UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='S. M. Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Carvalho Silva, M';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, G.P.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='S. Aparecida Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, FSG';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MF da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. G. da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Carvalho-Silva, M.; Amorim, P.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MC';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, NT';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='T. Macambo-Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Machado Silva, T.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Machado-Silva, T';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='F. Silva Filho';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='F. Bonadeu da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MCR';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho-Silva/X-2007';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, ACB';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='MICHELINE CARVALHO-SILVA';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho-Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='G. Pereira-Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Carvalho-Silva, M.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Macedo-Silva, T.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M.Carvalho-Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Carvalho-Silva, M; Pereira, LA';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, C.A.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, R.K.; Seidinger. L.C.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, ACC';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho-Silva/Fev.-2008';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, CAS';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho-Silva/10-08-2006';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, CAS da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho-Silva, C.C. Silva, et. all';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, S.M.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, BG';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, M.G.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Mattos Silva, LA';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho-Silva/X-2006';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MC da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Micheline Carvalho Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Da Silva, D.R.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. C. Silva & C. Sinigaglia';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho Silva/10-08-2006';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva; Carvalho, M';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Carvalho-Silva M';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Soares-Silva, J. P.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='A. G. da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, T.M.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MFF da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M.F.O. Silva et Galvão, M.N.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='N. T. da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M.C. Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MR';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='G. Pereira-Silva & M. Carvalho-Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Fleury-Silva, H.R.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, CSA da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='A. S. L. da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='G. P. Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Soares-Silva, J.P.; Sampaio, D.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, DCG';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva Neto, S.J.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, SM';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, M.C.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. Carvalho Silva/X-2008';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M. A. da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Caralho Silva, M.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Machado-Silva, T.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, ACC; Melo, A';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, NT da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='M.A. da Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Guedes, ML; Silva, LM; Akita, AST';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Carvalho-Silva, M';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, MG da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, TT';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Bernardi, P.T.; Mendes, N.A.; Schinato, F.; Silva, A.L.';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Machado-Silva';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva, M da';
UPDATE public.trusted_identifier set selected=false where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='Silva';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E. F. et Dmonteiro';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/Jan.2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='J.Wesenberg, E.F. Guimarães/02-XII-2009';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães EF; Ichaso CLF';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.; Ichaso, C.L.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães; C. L. F. Ichaso';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='D. M. Ferreira; E. F. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.; Queiroz, G.A.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Ichaso, C.L.; Guimarães, E.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Ichaso, CLF; Guimarães, EF';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.; Ichaso, C.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães; R. Callejas Posada';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/2005';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.; Ichaso, C.L.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Wesenberg, J';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães & V.B. Sarnaglia-Jr.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='L.A.Pereira & E.F. Guimarães/24-01-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.Guimarães/1992';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='C. L. F. Ichaso; E. F. GuimarÃ£es';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães EF';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='H. d. C. Monteiro Filho';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='J. Monteiro';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro, J';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro, O';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro, OP';
UPDATE public.trusted_identifier set selected=false where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='R.Monteiro';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, O.';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimaraes';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; V. Catarelli';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='L.A.Pereira & E.F. Guimarães/25-01-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/Out.2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães E.F.; Ferreira, D.M.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.; Ichaso, C.L.F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.; Sanaglia';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimar~eas, E.F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/VII-2011';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/2019';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães, E. Medeiros';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães/2009';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. GuimarÃ£es';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.G.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.; Ferreira, D.M.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F.Guimarães/2009';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Ferreira, DM';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães-I/2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='D. M. Cavalcanti Ferreira; E. F. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.; Queiroz, G.A.';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='D. Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='O.A. Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, W.';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EL';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Tais B. Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.K.';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='T. S. Mendes & E.Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, L';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, O';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='O. A. Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/15-05-2013';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães/2008';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F.Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/IV-2006';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='C. L. F. Ichaso; E. F. Guimarães';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães/2000';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães/junho.2008';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães-Jan.2008';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.';
UPDATE public.trusted_identifier set selected=false where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, O.; Ichaso, C.';
UPDATE public.trusted_identifier set selected=false where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='H. Medeiros';
UPDATE public.trusted_identifier set selected=false where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='Medeiros';
UPDATE public.trusted_identifier set selected=false where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='Medeiros, H';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='L.N.Sátiro & L.P.de Queiroz';
UPDATE public.trusted_identifier set selected=true where fullname='Eric J Tepe' and search='Tepe' and value_founded='Tepe EJ';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='G. A. Queiroz';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='G.A. Queiroz';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='G.A. Queiroz/2018';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Guimarães, E.F.; Queiroz, G.A.';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Guimarães, E.; Queiroz, G.A.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães/2006';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F.Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F.Guimarães & D.Monteiro/04';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E. .F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Carvalho, M';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/Agos.1991';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães E.F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/2016';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.; Sarnaglia Júnior, V.B.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Callejas, R';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimar~eas, E.F.; Ferreira, D.M.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/2006';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães; D. M. Ferreira';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Monteiro, D';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E.F.; Costa, C.G.; Falcão, C.L.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães/10-10-2007';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='V. Catarelli; E. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/1991';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='L.A.Pereira & E.F. Guimarães/17-01-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães/ 1995';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães,E.F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimarães - 5/1/2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='L.A.Pereira & E.F. Guimarães/26-03-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie Franklin Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F.Guimarães & D.M. Ferreira/2006';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E. & Ichaso, C.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F.Guimarães/2006';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/2007';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/1992';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E. & Ichaso,C.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Carvalho, MS';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F.GUIMARÃES';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. GuimarÃ£es; C. L. F. Ichaso';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='R. Callejas Posada; E. F. GuimarÃ£es';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. Guimarães/2001';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães/2018';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, E. F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Guimarães, EF; Medeiros, E von S.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/2003';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. Guimarães/2009';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='L. P. de Queiroz';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='L.P.de Queiroz';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='M.H. de Queiroz';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz, EP';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz, LP de';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz, M.H. de';
UPDATE public.trusted_identifier set selected=false where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz, MN';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho, MLS';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='J.G.de Carvalho-Sobrinho';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho, AM de';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Silva; Carvalho, M';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Guimarães, EF; Carvalho, MS';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Guimarães, EF; Carvalho, M';
UPDATE public.trusted_identifier set selected=false where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho, MS';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho-Silva';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M.Carvalho-Silva';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho-Silva/Fev.-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho-Silva M';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker, T.G.';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='W. Trelease; T. G. Yuncker';
UPDATE public.trusted_identifier set selected=true where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='Medeiros, E von S';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho-Silva/X-2007';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='G Yuncker, T.';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho-Silva, M';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='R. Callejas Posada';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='T. G.Yuncker';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro, D.';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Guimarães, E. F. et Dmonteiro';
UPDATE public.trusted_identifier set selected=true where fullname='Daniel Ruschel' and search='Ruschel' and value_founded='Daniel Rruschel';
UPDATE public.trusted_identifier set selected=true where fullname='Daniel Ruschel' and search='Ruschel' and value_founded='D. Ruschell';
UPDATE public.trusted_identifier set selected=true where fullname='Daniel Ruschel' and search='Ruschel' and value_founded='Ruschel, D.';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/X-2014';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='R. Callejas';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='R.Callejas';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Guimarães, EF; Callejas, R';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='R. Callejas/1993';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Callejas';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Callejas, R; Garcia, AR';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Ricardo Callejas';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Callejas, R';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Callejas, R.';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='R. Callejas/1994';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='et al.; Callejas, R';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Micheline Carvalho Silva';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho, M';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho Silva/10-08-2006';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho Silva, M';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho, M.S.';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz, G.A.';
UPDATE public.trusted_identifier set selected=true where fullname='George Azevedo de Queiroz' and search='Queiroz' and value_founded='Queiroz, G.A. de';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho-Silva, C.C. Silva, et. all';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho Silva/X-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='Elsie F. Guimaraes';
UPDATE public.trusted_identifier set selected=true where fullname='Eric J Tepe' and search='Tepe' and value_founded='Tepe, EJ';
UPDATE public.trusted_identifier set selected=true where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='Guimarães, EF; Medeiros, E von S.';
UPDATE public.trusted_identifier set selected=true where fullname='Eric J Tepe' and search='Tepe' and value_founded='E. J. Tepe';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, O.; Ichaso, C.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Ichaso, CL';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Ichaso, CLF';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Ichaso, C.L.; Guimarães, E.';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Daniele Monteiro';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker TG';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='Trelease, W.; Yuncker, T. G.';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='W. Trelease; T. G. Yuncker';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker, TG';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/15-06-2012';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/20-06-2012';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/2011';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/26-03-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/Março-2008';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='Trelease';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='Trelease, W';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='C. L. F. Ichaso';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='G. Pereira-Silva & M. Carvalho-Silva';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='E. F. Guimarães; R. Callejas Posada';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='R. Callejas Posada; E. F. GuimarÃ£es';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker TG; Trelease W';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Trelease, W.; Yuncker, T. G.';
UPDATE public.trusted_identifier set selected=true where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='Medeiros, ESS';
UPDATE public.trusted_identifier set selected=true where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='Medeiros, E von S.';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='MICHELINE CARVALHO-SILVA';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho-Silva, M.';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho-Silva/10-08-2006';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='M. Carvalho-Silva/X-2006';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='T. G. Yuncker';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker, T. G.';
UPDATE public.trusted_identifier set selected=true where fullname='Ricardo de la Merced Callejas Posada' and search='Callejas' and value_founded='Callejas Posada R';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker,T.G.';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro, D';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Monteiro, D.M.';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='E.F.Guimarães & D.Monteiro/04';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Guimarães, EF; Monteiro, D';
UPDATE public.trusted_identifier set selected=true where fullname='Daniel Ruschel' and search='Ruschel' and value_founded='Daniel Ruschel';
UPDATE public.trusted_identifier set selected=true where fullname='Daniel Ruschel' and search='Ruschel' and value_founded='Ruschel, D';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. Guimaraes & C. L. Ichas';
UPDATE public.trusted_identifier set selected=true where fullname='Eric J Tepe' and search='Tepe' and value_founded='Tepe, E.J.';
UPDATE public.trusted_identifier set selected=true where fullname='Erika Von Sohsten de Souza Medeiros' and search='Medeiros' and value_founded='E. F. Guimarães, E. Medeiros';
UPDATE public.trusted_identifier set selected=true where fullname='Eric J Tepe' and search='Tepe' and value_founded='R. C. Foster; E. J. Tepe';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho-Silva, M.; Amorim, P.';
UPDATE public.trusted_identifier set selected=true where fullname='Micheline Carvalho-Silva' and search='Carvalho' and value_founded='Carvalho-Silva, M; Pereira, LA';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Ichaso, C.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Ichaso CLF';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Ichaso, CLF; Guimarães, EF';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='Daniela Monteiro';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. F. Monteiro';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='Yuncker TG; Trelease W';
UPDATE public.trusted_identifier set selected=true where fullname='Aline Vieira de Melo Silva' and search='Silva' and value_founded='A. V. de Melo Silva';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D.Monteiro';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D.Monteiro/15-06-2012';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/2008';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/25-03-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/III-2008';
UPDATE public.trusted_identifier set selected=true where fullname='Daniele Monteiro Ferreira' and search='Monteiro' and value_founded='D. Monteiro/VI-2011';
UPDATE public.trusted_identifier set selected=true where fullname='Truman George Yuncker' and search='Yuncker' and value_founded='Yuncker';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='Trelease W';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='Trelease, W.';
UPDATE public.trusted_identifier set selected=true where fullname='William Trelease' and search='Trelease' and value_founded='W. Trelease';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='C. L. F. Ichaso; E. F. GuimarÃ£es';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='C. L. F. Ichaso; E. F. Guimarães';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='E. F. GuimarÃ£es; C. L. F. Ichaso';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='E. F. Guimarães; C. L. F. Ichaso';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, E.F.; Ichaso, C.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, E.F.; Ichaso, C.L.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães EF; Ichaso CLF';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, E. & Ichaso, C.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, E. & Ichaso,C.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, E.; Ichaso, C.L.';
UPDATE public.trusted_identifier set selected=true where fullname='Carmen Lúcia Falcão Ichaso' and search='Ichaso' and value_founded='Guimarães, E.; Ichaso, C.L.F.';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E.F. Guimarães & G.A. Queirox/2017';
UPDATE public.trusted_identifier set selected=true where fullname='Elsie Franklin Guimarães' and search='Guimar' and value_founded='E. F. Guimarães/Agosto.1991';
